### ISSUE TITLE
Use the Org object's 'sending_allowed' key to block or allow sending of messages from the clients

### ISSUE THREAD

**Issue by misskniss** [ForstaLabs/relay-web-app#125]
We have a new key on the Org object that is set by the Stripe/Billing feature.

sending_allowed == true: the payment information for the org is up to date and valid so all members of the org can send and recv messages

sending_allowed == false: the payment information is incorrect/we have not been paid and the 30-day grace period for updating the card has passed so members of this org are not allowed to send/recv messages anymore. 

- The clients need to check for this setting and not allow sending of messages if it is set to false. 
- If the user tries to send a message while the setting is false, hand them a notification that reads:

> Message not sent. This organization is Inactive. Please contact your organization administrator for details.

**Comment by mayfield** [comment]
Message sending will always be unregulated now.
