### ISSUE TITLE
Mobile Web browser on iOS doesn't "Send" when pressed.

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#128]
Trying to send a message.  I select user, type in a message, and hit send.  One of the wings of the paper airplane flutters, but doesn't send.

I am still receiving messages on the same web browser, so connectivity with system appears to be working.

Replicated with both Chrome and Safari

**Comment by mayfield** [comment]
Let's close the loop on this today and close it if it's not real.
