### ISSUE TITLE
image view positioning

### ISSUE THREAD

**Issue by gregperk** [ForstaLabs/relay-web-app#130]
I am using Safari on production.

If I receive an image attachment and double-click to view it larger, it isn't centered in the view and I can't access the image's controls:
<img width="1486" alt="screen shot 2017-11-01 at 1 03 02 pm" src="https://user-images.githubusercontent.com/1587163/32292319-5615a7c6-bf05-11e7-8967-e8c54b61493e.png">

But if I then do (any) resize event, it is suddenly positioned correctly:
<img width="1464" alt="screen shot 2017-11-01 at 1 03 13 pm" src="https://user-images.githubusercontent.com/1587163/32292318-56013458-bf05-11e7-97a3-292e719fdd74.png">

**Comment by mayfield** [comment]
Rumor has it that the new semantic-u fixes this.
