### ISSUE TITLE
Video upload playback looks broken depending on the filetype 

### ISSUE THREAD

**Issue by misskniss** [ForstaLabs/relay-web-app#132]
After uploading a .mov file from an Android App, I was not able to get it to play in a Chrome browser in the web app. Greg was able to sort of get it to open but it would only move one frame per click if his mouse in Safari.

I uploaded the same file but as a .mp4 from my desktop to the instance running in Chrome and it played and previewed as I would expect. 

Without presenting a reason to the user for why the .mov file won't play, it looks like we are broken (because it will play normally on their phone). We should find a way to make the webapp play this file type normally or tell the user we cannot play this file type and instead offer to let them download it. 

The .mov file was on my phone because someone had taken the video with their iPhone and shared it with me.  When they shared it will me over a text message, I got a link that sent me to iCloud which then let me download the video to my android phone. Which means that this link sharing for larger videos among iOS users is a standard way of sharing these files for them and likely to be common practice for iOS owners. 

The .mp4 on my phone was there because I had uploaded the .mov file to my Google Drive, which automatically converted it to an .mp4, which I then downloaded onto my desktop to post in the web app. 

![mov vs mp4 in webapp](https://user-images.githubusercontent.com/2394436/32296343-9946f494-bf11-11e7-8c99-92c7d61d0e0c.png)

[Test Files Can Be Downloaded Here](https://drive.google.com/drive/folders/0BzYP1j6rWC2_WVFOSlJWbXcybUk?usp=sharing)

**Comment by mayfield** [comment]
Can't reproduce.
