### ISSUE TITLE
Allow a user to cancel a pending Jump Start invite (rescind the message content in the queue)

### ISSUE THREAD

**Issue by misskniss** [ForstaLabs/relay-web-app#139]
@misskniss commented on [Mon Nov 06 2017](https://github.com/ForstaLabs/ccsm-api/issues/320)

Some users will want to cancel a pending invite. We should listen for a 'Cancel' event and drop any pending messages waiting in queue from this sender to the invitee. 

Use Case: Inviter changes their mind about the invite/message.
Provide a way to cancel the invite - **thus not deliver the pending message payload to the invitee** in case the invited user does create an account. The user that would have received a message on account creation should be given some indication that the content associated with the invite was deleted by the inviter. The inviter should see that the invite was rescinded and that the message that would have been delivered has been dropped/deleted. 

For example: Maybe the conversation view exists for the user that was invited but when they go to it there is just an info message that reads: ```Content was deleted by the sender.```

**Comment by mayfield** [comment]
Covered by message delete and thread delete.
