### ISSUE TITLE
Search for users with a match phone number before offering the Jump Start invite option

### ISSUE THREAD

**Issue by misskniss** [ForstaLabs/relay-web-app#140]
We want to check for users that already exist with a phone number that someone is trying to use to invite a user to the system. (otherwise we currently will force an invited user to create a new account to receive the message intended for them - even if they are already on the system. I the invited user does not create a new account, they never receive the message intended for them. Yikes.)

* As a user that is trying to invite someone enters a phone number, we should be looking to see if that phone number belongs to one or more active accounts already in system.
* If there are matching accounts, we should present those to the inviter to choose from instead of sending them yet another invite. 
* If they chose an existing account, we send the message intended for them normally. If there is not an account already in system with that number (and the phone # is valid) we send the Jump Start invite normally.

**Comment by mayfield** [comment]
Done!
