### ISSUE TITLE
A few Defects in Public Org (now called "Forsta")

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#154]
A few things I saw looking through web app:

1. In the left hand "Forsta" menu, all of the menu selections are available, when it should only be "Edit Profile"

2. Under "Message History" (which shouldn't be visible on "forsta" org), it appears "On the Record" is on.

3. "On the Record" appears to be selectable (although it doesn't allow the setting to be changed)

**Comment by mayfield** [comment]
Most of this is fixed on dev as of just now actually.  The message history is... history (PUN!) and on the record is sort of getting transformed to "has vault users".  We'll explain in the next few days..
