### ISSUE TITLE
Contact list doesn't remember contacts outside of org

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#159]
If I send a message to somebody outside of org, it doesn't autofill when I try adding same person into another conversation.  For example, even though pi.bot:forsta has been in numerous discussions, I still need to write out the entire address every time.

Ideally, contacts that have been messaged should be selected as part of autofill, or perhaps there could be an "Add to Contacts" if the user wants to add them to their contact list. This is more complex until we have some ability to store this info somewhere.

RZ

**Comment by mayfield** [comment]
Done!
