### ISSUE TITLE
Ben doesn't see my messages from web messenger, I see his

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#161]
It appears on my screen that it has been delivered, but Ben doesn't see it.  Then Ben sends me a message and I receive it.

**Comment by benkline** [comment]
Received them on Android client. but they didn't show up on Web Messenger

**Comment by mayfield** [comment]
Looks like another `fetchMessages: false` issue in signal after talking with Ben about this..  will open an issue there.
