### ISSUE TITLE
provisioning snafus

### ISSUE THREAD

**Issue by benkline** [ForstaLabs/relay-web-app#169]
Please have the following ready before submitting a new bug issue...

- [x] Platform (os), Browser (with version), Stack (dev, stage, prod), App version (`/version`)
webapp v0.50.1 (49002ce9dd) and iOS 1.1.2(128)
- [x] Steps to reproduce
+ from QR code page. Go to link device from iOS App.
+ iOS would show a linked device link and the QR code would be replaced with the progress bar, but then the progress bar stopped after the first 'inch' or so. 
+ The only way to link a new device was to use the pi and delete the iOS app. 
+ Then after getting back in linked devices on webapp showed the iOS device as a linked device. but when I sent a message to myself from the webapp, it went into the device provisioning 15 sec wait and... GOTO START

- [x] Logs (text) from developer console.
- [x] Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1417632/34170669-ff51ed22-e4a8-11e7-82f5-4a0f8e1922e2.png)

**Comment by benkline** [comment]
https://github.com/ForstaLabs/relay-ios/issues/267

**Comment by mayfield** [comment]
Fixed in 4f01c0dfe0f767ebea819bd21fd934fb020226db
