### ISSUE TITLE
Member of thread but cannot message in it

### ISSUE THREAD

**Issue by Reywasbosch** [ForstaLabs/relay-web-app#172]
Windows/Google Chrome/Prod
I'm a member of of the WTF thread but cannot message in that thread through my web app.  I am able to message in that thread through my mobile app.
![image](https://user-images.githubusercontent.com/21366270/34574915-1f38d148-f136-11e7-80c2-61559c379137.png)

**Comment by mayfield** [comment]
Can you send the results of a `/tdump` in that thread and your username?

**Comment by Reywasbosch** [comment]
![image](https://user-images.githubusercontent.com/21366270/34579038-94a50f10-f144-11e7-9b7c-ef5aba66a80e.png)
