### ISSUE TITLE
Randomly receive messages on other devices, but not on web-app

### ISSUE THREAD

**Issue by benkline** [ForstaLabs/relay-web-app#174]
- [x] Platform (os), Browser (with version), Stack (dev, stage, prod), App version (`/version`)

macOS
Version 63.0.3239.132 (Official Build) (64-bit)
prod
v0.56.1 

- [x] Steps to reproduce
seems to happen randomly... is currently happening to Raino. 
sent messages are received on android or iOS device but not on web-app. notification showing not received. 

- [x] Logs (text) from developer console.

[app.forsta.io-1516038604680.txt](https://github.com/ForstaLabs/relay-web-app/files/1632562/app.forsta.io-1516038604680.txt)

- [ ] Screenshots (if applicable)

**Comment by mayfield** [comment]
Various fixes to the keys api on signal server probably helped fix this;  closing for now unless it pops up again.
