### ISSUE TITLE
Error when going to sign into Forsta

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#176]
Steps:
1. Click on "Sign In" button on Home page.  This redirects to https://app.forsta.io/@
2. Error: Invalid Token show (see attached screenshot)
![sign in error](https://user-images.githubusercontent.com/29361211/35651836-51e7746e-069e-11e8-9460-78ec19d1cc85.jpeg)

**Comment by mayfield** [comment]
logs?

**Comment by mayfield** [comment]
Nevermind, figured it out.  First time login straight to the @ link instead of / will do that.  Fixed.

**Comment by rainoz** [comment]
Great!  That was fast.
