### ISSUE TITLE
When using "/add" command line to add new member to a thread, show everyone in current org (don't need to show people in public org)

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#180]
This makes it easier to add (already works for /remove)

**Comment by mayfield** [comment]
The `@` completer isn't contextually aware.  We don't really have a framework for such intelligence.   As such it's a single behavior for any references to `@`.  One thought I had was that if you attempt tab completion to the point where no other results are found I could then search your entire contact database as a last resort.   Feedback welcome.

**Comment by rainoz** [comment]
To clarify:  You'd auto-fill based upon people in org first, then if that is unsuccessful put in all of the people from their contact list? Or use their entire contact list from the start?

You could also auto-fill entire contact list, but sort by people in-org first...

**Comment by mayfield** [comment]
It's presently based on the members of the current thread in two ways.  It includes all the individual members of the thread and it includes any tags referenced in the distribution.   In some cases these are the same but not always. 

My proposal is that if you begin to type `@some` and there are no tags starting with `some` using the aforementioned context, then it would look for any tags in your contacts that start with `@some`.  e.g it could offer up suggestions for `@somebody`, `@some:other.org`, etc even if those two suggestions are not presently in the thread.  

The most obvious con is that you might be confused into thinking that you're "mentioning" these contacts and that they may be notified in some way by the mere mention of their tag.  This is not the case given that the tags being mentioned are no in the thread and cannot be alerted to activity taking place on a thread they are not members of.

**Comment by rainoz** [comment]
I think that sounds like a good place to start.  Since /add is a somewhat
advanced function, hopefully those using it would have more knowledge (AND
the person who  is being added WILL get next messag).

A related idea would be if you type a "/" that it would show you what the
special commands available are.

Web app looking great!
RZ

**Comment by mayfield** [comment]
Fixed in 114ab555951f6750242834905c3a0fb2a80db166
