### ISSUE TITLE
Search for thread support

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#184]
Currently, the only choice when you search on a name is to message them.  Often you are looking for a list of the communication with that person.

It would be good to have the option to display the list of messages that the given person is in so that you can then select one of the threads to view and or continue discussions on.

This is how GMail and iMessage work.

**Comment by mayfield** [comment]
Requirements:
 1. search for thread title
 2. search for thread by distribution
 3. search for thread by membership

**Comment by mayfield** [comment]
Done
