### ISSUE TITLE
Idea on how to go to top of "new messages"

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#211]
I've been using WeChat for the past couple weeks.  One thing they do nicely is let you get to the first unread message of a thread.  If the new threads go above the top of the page, it provides a nice little arrow that brings the user to the top of the new messages.

See screenshot of how it looks on mobile.

![wechat new messages screenshot](https://user-images.githubusercontent.com/29361211/42104749-0249fe06-7b8b-11e8-8db7-a30a26c87ad5.png)

**Comment by mayfield** [comment]
Closing in favor of #233
