### ISSUE TITLE
Start with "Detached Window" for voice/video call

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#217]
I think the default view should be the small (or some size) detached view.  It would be more intuitive to go from this view to a "Full screen" view.  

It's not easy to figure out how to get to detached view since there's really 3 views:  "Detached", "Attached" (Not sure main use cases for this; might be able to get around by maybe allow to resize the detached", and then "Full screen" if you want to utilize your entire screen.

**Comment by mayfield** [comment]
I think I can do this,  will take some thought and compat testing..

**Comment by mayfield** [comment]
Fixed in ef4a79a928e0af5df5e1ee431fd36b064c4bbbac
