### ISSUE TITLE
Provide more elegant way for users to re-initiate a web messenger session.

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#221]
Have been hearing more frequently of people getting frozen out of web messenger with the QR Code.  

The message is:

**Hi Damond,

A request was made to link a new messaging device to the Forsta account @damond:bonocore.com.  If you did not initiate this action please contact <support@forsta.io>.

I keep getting this message when trying to log in from my computer.  

It then takes me to another page where it says:

Link Forsta Web using a Mobile App
Verify your identity with this QR code.
I have logged on from my PC before, but now it's not letting me.**

**Comment by mayfield** [comment]
This issue is from pre-provisioning changes.   The updated provisioning technique provides better recourse for clients in this scenario.
