### ISSUE TITLE
Invalid User (Ephemeral remnant or removed user) no longer has user info.  Would be nice to know who user was even after deletion

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#224]
When a user disappears from system, all of  their history disappears from view.  (See screenshot).

Ideally the history would still show who the user was when they were in the system, and maybe have something like "deleted user" or something similar as part of the description.  This history is particularly important in Live Chat, and also for users in general

When it says "Invalid User" there is no info there to piece together who was participating in a conversation.
![invalid user](https://user-images.githubusercontent.com/29361211/45375775-35baad00-b5b3-11e8-91e1-06ada4f288b1.jpeg)

**Comment by mayfield** [comment]
I'll modify the contact sync code to not purge delete contact info and instead just mark them as inactive/removed/invalid.

**Comment by mayfield** [comment]
Initial fix in 8da2def2e31883726c84daf05439997e63c60b2a
