### ISSUE TITLE
Copy and Paste from MS Word adds a lot of buffer (and isn't visible at all when you first past)

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#225]
In attached example, I copied one line of code from a MS Word document, and then pasted it into Web Messenger.

When I first pasted it, nothing was visible in the window.

When I hit "Send" this is what I saw.  For some reason there's a lot of padding around the one line of text
<img width="485" alt="ms word copy and paste into messenger" src="https://user-images.githubusercontent.com/29361211/46165892-02347f80-c24f-11e8-83a5-4ce53986890b.png">

**Comment by mayfield** [comment]
@rainoz Can you attach the copy buffer you were using to github for inspection?

**Comment by rainoz** [comment]
![image](https://user-images.githubusercontent.com/29361211/46171874-0d8fa700-c25f-11e8-9635-02999523edcf.png)

**Comment by rosew** [comment]
The same thing happens to me on a Mac. I coped the following from a mac console window:

```
HTTP GET /v1/user/ 200 [0.08, 172.17.0.1:36360]
```

When I pasted it into a message and hit send there was a bunch of white space
