### ISSUE TITLE
Need to notify people if they are on an unsupported browser

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#226]
Had a call today with a prospective customer/partner.  They had tried to set up an account on Forsta, and were hung using Edge.  

It would be great that is somebody is using an unsupported browser that they get an error message telling them that the browser isn't supported and recommending which ones are.

**Comment by mayfield** [comment]
Agreed.  I can probably get Edge to work in a degraded way soon.. I'll prioritize accordingly.
