### ISSUE TITLE
Show User.website URL when present in user cards.

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#227]
As a way to make it easier for people to manage a Forsta environment that includes a Message Vault, Compliance Monitor, and LIve Chat, it would be very helpful for an admin to add the URL to these Instances into the Admin Menu.

This way, anybody with Admin rights would be able to get to these different applications without needing to somehow remember what the URL's are.

One idea is that just like we have the "Admin" block of menu items, you could have a "Products" block of items that would include these items

**Comment by mayfield** [comment]
Blocked by ForstaLabs/atlas#409
