### ISSUE TITLE
Image file shows up upside down in Web Messenger

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#228]
Not sure what caused this, but this image was added to Messenger and it was rendered upside down.

I was able to replicate - in fact I also got it to show an image sideways rather than the right orientation

**Comment by rainoz** [comment]
Here's an image showing the image and also how it showed up in Messenger
![upside down image](https://user-images.githubusercontent.com/29361211/46441859-0d8f1b80-c725-11e8-8c66-5bfbd01595ca.jpeg)

**Comment by mayfield** [comment]
Can you upload the file?  I suspect it has exif tags that indicate it should be rotated and may have been large enough to require resizing.

**Comment by mayfield** [comment]
Not seeing that file.  Looks like you attempted to email it to github with an attachment.  I don't think that works.  Could you zip the file so it doesn't undergo any transformations and send it to me via forsta?

**Comment by mayfield** [comment]
[IMG_0590.jpg.zip](https://github.com/ForstaLabs/relay-web-app/files/2451040/IMG_0590.jpg.zip)
