### ISSUE TITLE
please indicate unread *replies*

### ISSUE THREAD

**Issue by gregperk** [ForstaLabs/relay-web-app#229]
Several times now I have missed replies that have arrived because there is no visual cue to tell me to go looking for them. 

Maybe they could be indicated in the thread's new-messages count and they could be rendered in a distinctive color until the next time the thread is opened... (NOT saying this is the preferred solution -- I'm just trying to start the ball rolling toward whatever the real solution might turn out to be.)

**Comment by mayfield** [comment]
Simpsons did it.
