### ISSUE TITLE
call loses participant on toggling detached-mode from a different thread

### ISSUE THREAD

**Issue by gregperk** [ForstaLabs/relay-web-app#232]
if I have a call running that started in one thread (say, with Mark), then go to another thread to message someone (say, with you) and toggle the call's detached-mode, I lose the other participant and have to restart the call.

**Comment by mayfield** [comment]
I can't repro this.  There is a small chance it was a different symptom of the bug fixed for #231.  Please reopen if you see this behavior persist following the fix from 3f4099947bbf2107f72cac49c84826871471687e.
