### ISSUE TITLE
Have separate buttons for Voice and Video

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#235]
It would be nice to have separate buttons for voice and video calls.  This could be either separate buttons like WhatsApp does (see attached), or as a drop-down where when you click the 'video' button it would let you choose voice, 
![img_9089](https://user-images.githubusercontent.com/29361211/49606992-0cab7d80-f952-11e8-893e-2614b5c45fee.PNG)

**Comment by mayfield** [comment]
done
