### ISSUE TITLE
Enhancement:  Enable voice/video invite to non-Forsta users

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#236]
Idea:  Be able to create an adhoc voice/video 'meeting' where non-Forsta users could be invited via SMS or email.  Not sure exactly how UI would look, but you would have a thread and then an "invite users" button where you input phone numbers or emails.  When the recipient clicked on link it would create an ephemeral client (like Live Chat) where they'd be prompted for name and then allowed to join call.

Not urgent feature, but I think this would be compelling.  We could then use Forsta to demo Forsta for prospective customers.

**Comment by mayfield** [comment]
Done
