### ISSUE TITLE
Link on "Products" tab on https://app.forsta.io/@signin  broken

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#237]
Needs to be renamed "Platform"  and go to https://forsta.io/platform/

**Comment by mayfield** [comment]
I already alerted Zach to the dead link issue, which should be resolved soon or now.  

For future reference, links baked into the apps must be "cool".  This is a point I've tried to stress numerous times, but it bears repeating..  https://www.w3.org/Provider/Style/URI

I will update the text to say platform but this is an anti pattern in general as noted above.

**Comment by mayfield** [comment]
@tyrocoders would you mind adding your name to your Github profile, I find it hard to remember which user you are.

**Comment by mayfield** [comment]
Fixed in 58b8c7665ca6256de8db9f57f20b83b6968a8d5a
