### ISSUE TITLE
"@xxxx" doesn't utilize a person's name

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#243]
In Web app in the message box,, I type in "@justin" because I want to select Justin from the list.  However, in the forsta.io org, Justin's name is @mayfield.  Therefore I get 3 other justins to choose from, but not the one that is in the org I am typing in.

Note - this works as expected in the "New message" dialog box.

**Comment by mayfield** [comment]
I'm not @justin in the forsta.io org.

**Comment by rainoz** [comment]
I understand.  The idea behind the defect is that I may not know your
username, and only know your real name.  If I start typing "Justin" it
should find you.  Often you won't know a person's username, especially in a
big org.  If I type in a name (First or last) it should be one of the
criteria for what names are presented.

Not a high priority item, but just wanted to note it.
