### ISSUE TITLE
call button is offered but does not work when a call from another thread is running

### ISSUE THREAD

**Issue by gregperk** [ForstaLabs/relay-web-app#246]
If a call is started and the user moves to another thread, there is a call button presented for this new thread. But pressing that button doesn't dump the existing call (even if everyone has left) to create a call for the new thread. So perhaps the call button should be inactive until the call window is closed, or it should have the power to replace the existing call.

**Comment by gregperk** [comment]
update from John: maybe a little surprising is that pressing the call button presented in another thread doesn't call the participants of that other thread, but just offers to the original thread's participants again

**Comment by mayfield** [comment]
Multi call is working now.
