### ISSUE TITLE
404 Loading gravatar icon in embed iframe - Chrome

### ISSUE THREAD

**Issue by nsbuckner** [ForstaLabs/relay-web-app#251]
Please have the following ready before submitting a new bug issue...

- [X] Platform (os), Browser (with version), Stack (dev, stage, prod), App version (`/version`)
Platform: Windows 10 Pro, version 1803
Browser: Chrome 72.0.3626.119
Stack: prod
App version: 0.81.0
- [X] Steps to reproduce
Connect to embed, once connection is established you get this error. Causes strange issues when using embed in an iframe. This is only happening in Chrome, works fine in Firefox.
- [X] Logs (text) from developer console.
See attached
- [X] Screenshots (if applicable)
See attached

[gravatar_error.log](https://github.com/ForstaLabs/relay-web-app/files/2913477/gravatar_error.log)

![image](https://user-images.githubusercontent.com/611577/53542697-e4f52d00-3adc-11e9-81a1-6016fe4234bc.png)

**Comment by mayfield** [comment]
That's normal.  It's just a 404 for user that doesn't have an avatar.  The error is handled and dealt with accordingly.  I usually disable network logging in the console because it incorrectly assumes any non 200 response is bad.

**Comment by nsbuckner** [comment]
Perfect. Thanks, Justin!
