### ISSUE TITLE
Change default textarea placeholder to "Type Message Here" in embed client

### ISSUE THREAD

**Issue by Zach-Richardson** [ForstaLabs/relay-web-app#257]
May we please change the default placeholder text from "Send Message to [Thread Title || Participants]" to "Type Message Here" in the embed client?

**Comment by mayfield** [comment]
I thought you already did this?

**Comment by Zach-Richardson** [comment]
I made it a configuration but not default. I assigned this card to me in Trello. Meant to assign this issue to me. It's a quick fix for me.
