### ISSUE TITLE
UI pauses become painful as (unarchived) threadcount grows?

### ISSUE THREAD

**Issue by gregperk** [ForstaLabs/relay-web-app#258]
I noticed that after I've let older threads (typically unpinned and not active) accumulate on the left hand side "below the fold" and out of sight, that the pauses to switch the view between the threads I do use can grow to be really long (several seconds). 

Archiving those below-the-fold threads seemed to make things all snappy again, so I wonder if there is an opportunity for an optimization to make that sort of manual housecleaning less necessary and more optional.

**Comment by mayfield** [comment]
what's your `F.foundation.allThreads.length` ?

**Comment by gregperk** [comment]
Currently 48

**Comment by gregperk** [comment]
(So that's the tolerable number -- before it was many more.)

**Comment by gregperk** [comment]
Looking at the list of archived threads, the count on that is about 273.

**Comment by gregperk** [comment]
(And I did almost all of those in one fell swoop to see if it would reduce
the pauses, IIRC.)

**Comment by mayfield** [comment]
So you had somewhere over 300 when it was slow?  I'll try to repro with that many and if it's a real perf problem I'll have to implement paging.  But I'm not likely to get to it soon, cause it will be a regression hotspot.

**Comment by gregperk** [comment]
+1

**Comment by mayfield** [comment]
I had to create nearly 1,400 threads to observe any perf degradation on my system.  And the perf impact was to the browsers rendering engine, and not a significant impact on thread selection or loading.   I could use some more performance data if you are able to collect it.  

Namely a devtools performance profile capture from the devtools.

**Comment by gregperk** [comment]
Restoring a thread seems to take about 8 seconds each, so restoring a few hundred to gather that would be pretty unfun.. 

Would thread info from the rendered summary be helpful in generating closer test data?

Attached is json of a list containing the innerHTML of the content element in each of them..
[data.txt](https://github.com/ForstaLabs/relay-web-app/files/3040707/data.txt)

**Comment by mayfield** [comment]
More info isn't likely to help.  I suspect your platform is getting slowed
down by some energy mgmt quote business.  My platform isn't subjecting me
to the same constraints.
