### ISSUE TITLE
If somebody is invited to a video call but joins late, there is no information that there is no signal that a video call is going

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#264]

**Comment by mayfield** [comment]
I'm not understanding.

**Comment by rainoz** [comment]
Scenario:  
1. I invite Pat and Justin to a conversation
2. Justin joins right away.  I initiate a video call for the thread.  Justin and Raino are in a video call
3. Pat joins some time later.  He sees the standard chat interface.  Has no idea there is a video call going on (and likely will just sit there not knowing what is happening.

Ideally if the thread is in video conference, somebody who comes to that chat knows what is happening, and maybe is brought into the video conference.

**Comment by rainoz** [comment]
Note - for some reason when I started this issue, it saved it without letting me add the description... Might have been operator error.

**Comment by mayfield** [comment]
Resolved?  I added code to denote a thread is engaged in a call in the background in both the nav and in the header of an opened thread.
