### ISSUE TITLE
Camera is on.  I can't find which conversation it belongs to

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#273]
I was part of a video call.    I believe I shut down the call (or maybe archived the thread).  My camera is still on on my iMac.

A couple things that might be happening:
1. I archived a message that had a video call on it, so there's no way I can find it (or turn off the camera on my computer), other than killing the tab
2. The conversation is in one of my active threads, but I have no idea which, so can't find the thread to go turn it off.

It would be great if there was a way I could easily see/find which thread has video on, or be able to kill the video feed on my browser tab without needing to kill Forsta session

**Comment by mayfield** [comment]
Partially addressed with #277
