### ISSUE TITLE
Show volume level for self pre call join

### ISSUE THREAD

**Issue by mayfield** [ForstaLabs/relay-web-app#289]

**Comment by rosew** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [We need to start calls with the ability to check call/network/device health.](https://trello.com/c/DSEGN2D4/46-we-need-to-start-calls-with-the-ability-to-check-call-network-device-health)

**Comment by rosew** [comment]
I'm assuming this is the same one I was about to create: "Show the call volume level before and during call. Volume should not require hovering over to see. "
