### ISSUE TITLE
Sending PDF in Messenger Screen

### ISSUE THREAD

**Issue by AndreaErickson22** [ForstaLabs/relay-web-app#308]
Sent a pdf from PC/Microsoft edge to Mac/Chrome was able to open on the mac, could not download the pdf or preview it on the PC, but opens right up on the mac. Also tried sending from the mac/chrome to the pc/edge, still could not download nor preview on Edge. Tried sending to the Iphone/Safari could not open nor download popped a blob error.

**Comment by mayfield** [comment]
Dup of #303
