### ISSUE TITLE
Discover messages from other devices (Sync Now feature)

### ISSUE THREAD

**Issue by mariahn** [ForstaLabs/relay-web-app#52]
Message history from Android app MIA after linking to web app. Expect to see entire message history.

- unlink web app
- send and receive messages
- link web app
- look for messages sent/received from mobile app in messenger and in message history

![image](https://user-images.githubusercontent.com/22178444/28584487-2a5258e2-712a-11e7-9679-c49e22ed3f25.png)

![image](https://user-images.githubusercontent.com/22178444/28584512-3c19ce66-712a-11e7-82d5-4e4cb9fbe1b3.png)

![message history no show](https://user-images.githubusercontent.com/22178444/28584449-09b30c12-712a-11e7-9b71-2296ba5c2f3a.PNG)

![message history no show2](https://user-images.githubusercontent.com/22178444/28584452-10ab437c-712a-11e7-98fe-04eac1128e2a.PNG)

Windows 10, Chrome
Droid Mini, Android 4.4.4

**Comment by mayfield** [comment]
Done did.
